// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAyzdWrz3N7eUZr10Sa-MmSPibwhvyXzx0',
    appId: '1:565057529163:web:7eff0ba2b5034f95dbb4ce',
    messagingSenderId: '565057529163',
    projectId: 'quicknotes-6b677',
    authDomain: 'quicknotes-6b677.firebaseapp.com',
    storageBucket: 'quicknotes-6b677.appspot.com',
    measurementId: 'G-08M19CS0QG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBhpk4TlaEOx--JMnKglPIAFP3t0Y97p6w',
    appId: '1:565057529163:android:6694d776d39362c3dbb4ce',
    messagingSenderId: '565057529163',
    projectId: 'quicknotes-6b677',
    storageBucket: 'quicknotes-6b677.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA-bj_UajdEn-ybv6Bq4cxNqKnYkTj6elU',
    appId: '1:565057529163:ios:bbc0a4d00675f479dbb4ce',
    messagingSenderId: '565057529163',
    projectId: 'quicknotes-6b677',
    storageBucket: 'quicknotes-6b677.appspot.com',
    iosClientId: '565057529163-7flb7714ghf35dg0romrh1gvdi7bka2i.apps.googleusercontent.com',
    iosBundleId: 'com.example.learningdart',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA-bj_UajdEn-ybv6Bq4cxNqKnYkTj6elU',
    appId: '1:565057529163:ios:c4ea3f452a21883fdbb4ce',
    messagingSenderId: '565057529163',
    projectId: 'quicknotes-6b677',
    storageBucket: 'quicknotes-6b677.appspot.com',
    iosClientId: '565057529163-1imdeuj0irbofel058opb933ghecdfln.apps.googleusercontent.com',
    iosBundleId: 'com.example.learningdart.RunnerTests',
  );
}
